services:
  server:
    image: ghcr.io/immich-app/immich-server:v2.3.1
    volumes:
      - ./data/upload:/data
    environment:
      - NODE_ENV=production
      - DB_HOSTNAME=postgres
      - DB_USERNAME=immich
      - DB_PASSWORD=immich
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
      - IMMICH_MACHINE_LEARNING_URL=http://machine-learning:3003
    depends_on:
      - redis
      - postgres
    restart: always
    ports:
      - "2283:2283"

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.3.1
    volumes:
      - ./data/model-cache:/cache
    environment:
      - NODE_ENV=production
    restart: always

  redis:
    image: valkey/valkey:8-bookworm
    restart: always
    volumes:
      - ./data/redis:/data

  postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      - POSTGRES_PASSWORD=immich
      - POSTGRES_USER=immich
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
